name: Test Python 3

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name : Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -e .[tests]

      - name: Show python dependencies
        run: |
          pip freeze

      - name: Run tests
        run: |
          ./run-tests.sh
